export const ACTIONTYPES = {
    CHANGE_SEARCHTERM: "CHANGE_SEARCHTERM",
    CHANGE_SELECTEDREGION: "CHANGE_SELECTEDREGION",
    FETCH_START: "FETCH_START",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_BORDERCOUNTRIES: "FETCH_BORDERCOUNTRIES",
    FETCH_ERROR: "FETCH_ERROR",
    FETCH_REGIONS: "FETCH_REGIONS",
    SEARCH_COUNTRY: "SEARCH_COUNTRY"
}